### ISSUE TITLE
Incorrect time displayed for frontend when request is made via PJAX/Turbolinks in Firefox

### ISSUE THREAD

**Issue by brandonweiss** [peek/peek-performance_bar#18]
This is what I'm seeing:

![y13i82j5ipnnsrylxzakiowaas7058mxm0fmnf6jlzy](https://cloud.githubusercontent.com/assets/4727/2907887/246a33a2-d621-11e3-9594-90e09bce8b7a.png)

The backend time is being correctly calculated, although it's being shoved offscreen because of the incorrect frontend time.

**Comment by dewski** [comment]
It's been resolved upstream, thanks for reporting.
